apiVersion: apps/v1
kind: Deployment
metadata:
  name: pwn200
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pwn200
  template:
    metadata:
      name: pwn200
      labels:
        app: pwn200
    spec:
      containers:
        - name: pwn200
          image: phx.ocir.io/ax8lv72xb3nu/bsidespdx2020/pwn200:latest
          imagePullPolicy: Always
          securityContext:
            privileged: false
          ports:
            - containerPort: 9999
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: ocirsecret
