apiVersion: v1
kind: Service
metadata:
  name: web100
  annotations:
    external-dns.alpha.kubernetes.io/hostname: heading-the-right-way.bsidespdxctf.party
spec:
  ports:
   - port: 8081
     targetPort: 8081
  selector:
    app: web100
  type: LoadBalancer
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: web100
spec:
  podSelector:
    matchLabels:
      app: web100
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - port: 8081
    from: []
