apiVersion: apps/v1
kind: Deployment
metadata:
  name: web100
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web100
  template:
    metadata:
      name: web100
      labels:
        app: web100
    spec:
      containers:
        - name: web100
          image: phx.ocir.io/ax8lv72xb3nu/bsidespdx2020/web100:latest
          imagePullPolicy: Always
          securityContext:
            privileged: false
          ports:
            - containerPort: 8081
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: ocirsecret
