apiVersion: v1
kind: Service
metadata:
  name: pwn100
  annotations:
    external-dns.alpha.kubernetes.io/hostname: basic-bof.bsidespdxctf.party
spec:
  ports:
   - port: 9999
     targetPort: 9999
  selector:
    app: pwn100
  type: LoadBalancer
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: pwn100
spec:
  podSelector:
    matchLabels:
      app: pwn100
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - port: 9999
    from: []
