apiVersion: v1
kind: Service
metadata:
  name: web200
  annotations:
    external-dns.alpha.kubernetes.io/hostname: socking-it-to-ya.bsidespdxctf.party
spec:
  ports:
  - name: mtls
    protocol: TCP
    port: 8081
    targetPort: 8081
  - name: http
    protocol: TCP
    port: 8082
    targetPort: 8082
  - name: socksproxy
    protocol: TCP
    port: 1080
    targetPort: 1080
  selector:
    app: web200
  type: LoadBalancer
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: web200
spec:
  podSelector:
    matchLabels:
      app: web200
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - port: 8081
    - port: 8082
    - port: 1080
    from: []
