apiVersion: v1
kind: Service
metadata:
  name: tor300
spec:
  ports:
   - port: 80
     targetPort: 80
  selector:
    app: tor300
  type: LoadBalancer
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: tor300
spec:
  podSelector:
    matchLabels:
      app: tor300
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - port: 80
    from: []
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
          - 169.254.169.254/32
          - 10.96.0.1/32
